<build>
    <plugins>
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.0.0</version>
            <configuration>
                <mainClass>com.example.MainClass</mainClass>
                <arguments>
                    <argument>-javaagent:/path/to/opentelemetry-javaagent.jar</argument>
                    <argument>-Dotel.exporter.otlp.endpoint=http://localhost:4317</argument>
                    <argument>-Dotel.resource.attributes=service.name=my-service</argument>
                </arguments>
            </configuration>
        </plugin>
    </plugins>
</build>
